import { type Feature } from "@shared/schema";
import archiver from "archiver";
import { Readable } from "stream";

export async function generateReactScaffold(
  problemStatement: string,
  features: Feature[]
): Promise<string> {
  const projectName = problemStatement
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, "")
    .replace(/\s+/g, "-")
    .slice(0, 50);

  const files = generateScaffoldFiles(projectName, problemStatement, features);
  
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const archive = archiver("zip", { zlib: { level: 9 } });
    
    archive.on("data", (chunk) => chunks.push(chunk));
    archive.on("end", () => {
      const buffer = Buffer.concat(chunks);
      resolve(buffer.toString("base64"));
    });
    archive.on("error", reject);

    // Add files to archive
    Object.entries(files).forEach(([path, content]) => {
      archive.append(content, { name: path });
    });

    archive.finalize();
  });
}

function generateScaffoldFiles(
  projectName: string,
  problemStatement: string,
  features: Feature[]
): Record<string, string> {
  const mvpFeatures = features.filter(f => f.priority === "mvp");
  const stretchFeatures = features.filter(f => f.priority === "stretch");

  return {
    "package.json": generatePackageJson(projectName),
    "README.md": generateReadme(projectName, problemStatement, features),
    "src/App.tsx": generateAppTsx(projectName, mvpFeatures),
    "src/main.tsx": generateMainTsx(),
    "src/index.css": generateIndexCss(),
    "index.html": generateIndexHtml(projectName),
    "vite.config.ts": generateViteConfig(),
    "tsconfig.json": generateTsConfig(),
    "tailwind.config.js": generateTailwindConfig(),
    "postcss.config.js": generatePostcssConfig(),
    ...generateComponentFiles(mvpFeatures),
  };
}

function generatePackageJson(projectName: string): string {
  return JSON.stringify({
    name: projectName,
    private: true,
    version: "0.0.0",
    type: "module",
    scripts: {
      dev: "vite",
      build: "tsc && vite build",
      preview: "vite preview",
    },
    dependencies: {
      react: "^18.2.0",
      "react-dom": "^18.2.0",
      "@types/react": "^18.2.0",
      "@types/react-dom": "^18.2.0",
    },
    devDependencies: {
      "@vitejs/plugin-react": "^4.0.3",
      typescript: "^5.0.2",
      vite: "^4.4.5",
      tailwindcss: "^3.3.0",
      autoprefixer: "^10.4.14",
      postcss: "^8.4.24",
    },
  }, null, 2);
}

function generateReadme(projectName: string, problemStatement: string, features: Feature[]): string {
  const mvpFeatures = features.filter(f => f.priority === "mvp");
  const stretchFeatures = features.filter(f => f.priority === "stretch");

  return `# ${projectName}

## Problem Statement
${problemStatement}

## Features

### MVP Features
${mvpFeatures.map((f, i) => `${i + 1}. **${f.title}** - ${f.description}`).join('\n')}

### Stretch Features
${stretchFeatures.map((f, i) => `${mvpFeatures.length + i + 1}. **${f.title}** - ${f.description}`).join('\n')}

## Getting Started

1. Install dependencies:
\`\`\`bash
npm install
\`\`\`

2. Start the development server:
\`\`\`bash
npm run dev
\`\`\`

3. Open [http://localhost:5173](http://localhost:5173) to view it in the browser.

## Tech Stack
${features.map(f => `- ${f.title}: ${f.techStack}`).join('\n')}

## Generated by HackPal
This project was generated using HackPal, an AI-powered hackathon assistant.
`;
}

function generateAppTsx(projectName: string, features: Feature[]): string {
  return `import React, { useState } from 'react';
import './index.css';

function App() {
  const [activeFeature, setActiveFeature] = useState<string>('');

  const features = ${JSON.stringify(features.map(f => ({
    title: f.title,
    description: f.description
  })), null, 2)};

  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4">
      <div className="max-w-4xl mx-auto">
        <header className="text-center mb-12">
          <h1 className="text-4xl font-bold text-gray-900 mb-4">
            ${projectName.split('-').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ')}
          </h1>
          <p className="text-xl text-gray-600 max-w-2xl mx-auto">
            A hackathon project generated with HackPal
          </p>
        </header>

        <main className="space-y-8">
          <section className="bg-white rounded-lg shadow-md p-6">
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Features</h2>
            <div className="grid md:grid-cols-2 gap-4">
              {features.map((feature, index) => (
                <div 
                  key={index}
                  className="border rounded-lg p-4 hover:shadow-md transition-shadow cursor-pointer"
                  onClick={() => setActiveFeature(activeFeature === feature.title ? '' : feature.title)}
                >
                  <h3 className="font-medium text-gray-900 mb-2">{feature.title}</h3>
                  {activeFeature === feature.title && (
                    <p className="text-gray-600 text-sm">{feature.description}</p>
                  )}
                </div>
              ))}
            </div>
          </section>

          <section className="bg-white rounded-lg shadow-md p-6">
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Getting Started</h2>
            <div className="prose text-gray-600">
              <p>This is your hackathon project scaffold. Start building your features:</p>
              <ol className="list-decimal list-inside space-y-2 mt-4">
                <li>Review the features above</li>
                <li>Start with the MVP features first</li>
                <li>Add your API integrations</li>
                <li>Customize the UI to match your vision</li>
              </ol>
            </div>
          </section>
        </main>
      </div>
    </div>
  );
}

export default App;`;
}

function generateMainTsx(): string {
  return `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);`;
}

function generateIndexCss(): string {
  return `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}`;
}

function generateIndexHtml(projectName: string): string {
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>`;
}

function generateViteConfig(): string {
  return `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
    host: true,
  },
})`;
}

function generateTsConfig(): string {
  return JSON.stringify({
    compilerOptions: {
      target: "ES2020",
      useDefineForClassFields: true,
      lib: ["ES2020", "DOM", "DOM.Iterable"],
      module: "ESNext",
      skipLibCheck: true,
      moduleResolution: "bundler",
      allowImportingTsExtensions: true,
      resolveJsonModule: true,
      isolatedModules: true,
      noEmit: true,
      jsx: "react-jsx",
      strict: true,
      noUnusedLocals: true,
      noUnusedParameters: true,
      noFallthroughCasesInSwitch: true
    },
    include: ["src"],
    references: [{ path: "./tsconfig.node.json" }]
  }, null, 2);
}

function generateTailwindConfig(): string {
  return `/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}`;
}

function generatePostcssConfig(): string {
  return `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}`;
}

function generateComponentFiles(features: Feature[]): Record<string, string> {
  const files: Record<string, string> = {};
  
  features.forEach((feature, index) => {
    const componentName = feature.title.replace(/[^a-zA-Z0-9]/g, '');
    files[`src/components/${componentName}.tsx`] = `import React from 'react';

interface ${componentName}Props {
  // Add your props here
}

export default function ${componentName}(props: ${componentName}Props) {
  return (
    <div className="p-4 border rounded-lg">
      <h3 className="text-lg font-semibold mb-2">${feature.title}</h3>
      <p className="text-gray-600">${feature.description}</p>
      <div className="mt-4 text-sm text-gray-500">
        Tech Stack: ${feature.techStack}
      </div>
    </div>
  );
}`;
  });
  
  return files;
}
